/*  Copyright (C) 2024 LubinLew
    SPDX short identifier: MIT

Permission is hereby granted, free of charge, to any person obtaining a copy of
 this software and associated documentation files (the “Software”), to deal in 
the Software without restriction, including without limitation the rights to use, 
copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the 
Software, and to permit persons to whom the Software is furnished to do so, 
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all 
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, 
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES 
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR 
OTHER DEALINGS IN THE SOFTWARE. */


#include <audit_hyperscan.hpp>

#include "redis_debug.hpp"
#include "redis_internal.hpp"
#include "redis_statement.hpp"

/*****************************************************************************/

static audit_hs_hdl_t* g_hs_handler = nullptr;

/*****************************************************************************/


bool redis_statement_init(void)
{
    if (!audit_hs_init()) {
        return false;
    }

    g_hs_handler = audit_hs_block_create();
    if (nullptr == g_hs_handler) {
        return false;
    }

    const static audit_hs_data_t _statements[] = {
    {2000 ,"^ACL\\s+CAT"                       ,"ACL"                     ,0 },
    {2001 ,"^ACL\\s+DELUSER"                   ,"ACL"                     ,0 },
    {2002 ,"^ACL\\s+DRYRUN"                    ,"ACL"                     ,0 },
    {2003 ,"^ACL\\s+GENPASS"                   ,"ACL"                     ,0 },
    {2004 ,"^ACL\\s+GETUSER"                   ,"ACL"                     ,0 },
    {2005 ,"^ACL\\s+LIST"                      ,"ACL"                     ,0 },
    {2006 ,"^ACL\\s+LOAD"                      ,"ACL"                     ,0 },
    {2007 ,"^ACL\\s+LOG"                       ,"ACL"                     ,0 },
    {2008 ,"^ACL\\s+SAVE"                      ,"ACL"                     ,0 },
    {2009 ,"^ACL\\s+SETUSER"                   ,"ACL"                     ,0 },
    {2010 ,"^ACL\\s+USERS"                     ,"ACL"                     ,0 },
    {2011 ,"^ACL\\s+WHOAMI"                    ,"ACL"                     ,0 },
    {2012 ,"^APPEND"                           ,"APPEND"                  ,0 },
    {2013 ,"^ASKING"                           ,"ASKING"                  ,0 },
    {2014 ,"^AUTH\\s"                          ,"AUTH"                    ,REDIS_CMD_TYPE_AUTH },
    {2015 ,"^BF\\.ADD"                         ,"BF"                      ,0 },
    {2016 ,"^BF\\.CARD"                        ,"BF"                      ,0 },
    {2017 ,"^BF\\.EXISTS"                      ,"BF"                      ,0 },
    {2018 ,"^BF\\.INFO"                        ,"BF"                      ,0 },
    {2019 ,"^BF\\.INSERT"                      ,"BF"                      ,0 },
    {2020 ,"^BF\\.LOADCHUNK"                   ,"BF"                      ,0 },
    {2021 ,"^BF\\.MADD"                        ,"BF"                      ,0 },
    {2022 ,"^BF\\.MEXISTS"                     ,"BF"                      ,0 },
    {2023 ,"^BF\\.RESERVE"                     ,"BF"                      ,0 },
    {2024 ,"^BF\\.SCANDUMP"                    ,"BF"                      ,0 },
    {2025 ,"^BGREWRITEAOF"                     ,"BGREWRITEAOF"            ,0 },
    {2026 ,"^BGSAVE"                           ,"BGSAVE"                  ,0 },
    {2027 ,"^BITCOUNT"                         ,"BITCOUNT"                ,0 },
    {2028 ,"^BITFIELD"                         ,"BITFIELD"                ,0 },
    {2029 ,"^BITFIELD_RO"                      ,"BITFIELD_RO"             ,0 },
    {2030 ,"^BITOP"                            ,"BITOP"                   ,0 },
    {2031 ,"^BITPOS"                           ,"BITPOS"                  ,0 },
    {2032 ,"^BLMOVE"                           ,"BLMOVE"                  ,0 },
    {2033 ,"^BLMPOP"                           ,"BLMPOP"                  ,0 },
    {2034 ,"^BLPOP"                            ,"BLPOP"                   ,0 },
    {2035 ,"^BRPOP"                            ,"BRPOP"                   ,0 },
    {2036 ,"^BRPOPLPUSH"                       ,"BRPOPLPUSH"              ,0 },
    {2037 ,"^BZMPOP"                           ,"BZMPOP"                  ,0 },
    {2038 ,"^BZPOPMAX"                         ,"BZPOPMAX"                ,0 },
    {2039 ,"^BZPOPMIN"                         ,"BZPOPMIN"                ,0 },
    {2040 ,"^CF\\.ADD"                         ,"CF"                      ,0 },
    {2041 ,"^CF\\.ADDNX"                       ,"CF"                      ,0 },
    {2042 ,"^CF\\.COUNT"                       ,"CF"                      ,0 },
    {2043 ,"^CF\\.DEL"                         ,"CF"                      ,0 },
    {2044 ,"^CF\\.EXISTS"                      ,"CF"                      ,0 },
    {2045 ,"^CF\\.INFO"                        ,"CF"                      ,0 },
    {2046 ,"^CF\\.INSERT"                      ,"CF"                      ,0 },
    {2047 ,"^CF\\.INSERTNX"                    ,"CF"                      ,0 },
    {2048 ,"^CF\\.LOADCHUNK"                   ,"CF"                      ,0 },
    {2049 ,"^CF\\.MEXISTS"                     ,"CF"                      ,0 },
    {2050 ,"^CF\\.RESERVE"                     ,"CF"                      ,0 },
    {2051 ,"^CF\\.SCANDUMP"                    ,"CF"                      ,0 },
    {2052 ,"^CLIENT\\s+CACHING"                ,"CLIENT"                  ,0 },
    {2053 ,"^CLIENT\\s+GETNAME"                ,"CLIENT"                  ,0 },
    {2054 ,"^CLIENT\\s+GETREDIR"               ,"CLIENT"                  ,0 },
    {2055 ,"^CLIENT\\s+ID"                     ,"CLIENT"                  ,0 },
    {2056 ,"^CLIENT\\s+INFO"                   ,"CLIENT"                  ,0 },
    {2057 ,"^CLIENT\\s+KILL"                   ,"CLIENT"                  ,0 },
    {2058 ,"^CLIENT\\s+LIST"                   ,"CLIENT"                  ,0 },
    {2059 ,"^CLIENT\\s+NO-EVICT"               ,"CLIENT"                  ,0 },
    {2060 ,"^CLIENT\\s+NO-TOUCH"               ,"CLIENT"                  ,0 },
    {2061 ,"^CLIENT\\s+PAUSE"                  ,"CLIENT"                  ,0 },
    {2062 ,"^CLIENT\\s+REPLY"                  ,"CLIENT"                  ,0 },
    {2063 ,"^CLIENT\\s+SETINFO"                ,"CLIENT"                  ,0 },
    {2064 ,"^CLIENT\\s+SETNAME"                ,"CLIENT"                  ,0 },
    {2065 ,"^CLIENT\\s+TRACKING"               ,"CLIENT"                  ,0 },
    {2066 ,"^CLIENT\\s+TRACKINGINFO"           ,"CLIENT"                  ,0 },
    {2067 ,"^CLIENT\\s+UNBLOCK"                ,"CLIENT"                  ,0 },
    {2068 ,"^CLIENT\\s+UNPAUSE"                ,"CLIENT"                  ,0 },
    {2069 ,"^CLUSTER\\s+ADDSLOTS"              ,"CLUSTER"                 ,0 },
    {2070 ,"^CLUSTER\\s+ADDSLOTSRANGE"         ,"CLUSTER"                 ,0 },
    {2071 ,"^CLUSTER\\s+BUMPEPOCH"             ,"CLUSTER"                 ,0 },
    {2072 ,"^CLUSTER\\s+COUNT-FAILURE-REPORTS" ,"CLUSTER"                 ,0 },
    {2073 ,"^CLUSTER\\s+COUNTKEYSINSLOT"       ,"CLUSTER"                 ,0 },
    {2074 ,"^CLUSTER\\s+DELSLOTS"              ,"CLUSTER"                 ,0 },
    {2075 ,"^CLUSTER\\s+DELSLOTSRANGE"         ,"CLUSTER"                 ,0 },
    {2076 ,"^CLUSTER\\s+FAILOVER"              ,"CLUSTER"                 ,0 },
    {2077 ,"^CLUSTER\\s+FLUSHSLOTS"            ,"CLUSTER"                 ,0 },
    {2078 ,"^CLUSTER\\s+FORGET"                ,"CLUSTER"                 ,0 },
    {2079 ,"^CLUSTER\\s+GETKEYSINSLOT"         ,"CLUSTER"                 ,0 },
    {2080 ,"^CLUSTER\\s+INFO"                  ,"CLUSTER"                 ,0 },
    {2081 ,"^CLUSTER\\s+KEYSLOT"               ,"CLUSTER"                 ,0 },
    {2082 ,"^CLUSTER\\s+LINKS"                 ,"CLUSTER"                 ,0 },
    {2083 ,"^CLUSTER\\s+MEET"                  ,"CLUSTER"                 ,0 },
    {2084 ,"^CLUSTER\\s+MYID"                  ,"CLUSTER"                 ,0 },
    {2085 ,"^CLUSTER\\s+MYSHARDID"             ,"CLUSTER"                 ,0 },
    {2086 ,"^CLUSTER\\s+NODES"                 ,"CLUSTER"                 ,0 },
    {2087 ,"^CLUSTER\\s+REPLICAS"              ,"CLUSTER"                 ,0 },
    {2088 ,"^CLUSTER\\s+REPLICATE"             ,"CLUSTER"                 ,0 },
    {2089 ,"^CLUSTER\\s+RESET"                 ,"CLUSTER"                 ,0 },
    {2090 ,"^CLUSTER\\s+SAVECONFIG"            ,"CLUSTER"                 ,0 },
    {2091 ,"^CLUSTER\\s+SET-CONFIG-EPOCH"      ,"CLUSTER"                 ,0 },
    {2092 ,"^CLUSTER\\s+SETSLOT"               ,"CLUSTER"                 ,0 },
    {2093 ,"^CLUSTER\\s+SHARDS"                ,"CLUSTER"                 ,0 },
    {2094 ,"^CLUSTER\\s+SLAVES"                ,"CLUSTER"                 ,0 },
    {2095 ,"^CLUSTER\\s+SLOTS"                 ,"CLUSTER"                 ,0 },
    {2096 ,"^CMS\\.INCRBY"                     ,"CMS"                     ,0 },
    {2097 ,"^CMS\\.INFO"                       ,"CMS"                     ,0 },
    {2098 ,"^CMS\\.INITBYDIM"                  ,"CMS"                     ,0 },
    {2099 ,"^CMS\\.INITBYPROB"                 ,"CMS"                     ,0 },
    {2100 ,"^CMS\\.MERGE"                      ,"CMS"                     ,0 },
    {2101 ,"^CMS\\.QUERY"                      ,"CMS"                     ,0 },
    {2102 ,"^COMMAND"                          ,"COMMAND"                 ,0 },
    {2103 ,"^COMMAND\\s+COUNT"                 ,"COMMAND"                 ,0 },
    {2104 ,"^COMMAND\\s+DOCS"                  ,"COMMAND"                 ,0 },
    {2105 ,"^COMMAND\\s+GETKEYS"               ,"COMMAND"                 ,0 },
    {2106 ,"^COMMAND\\s+GETKEYSANDFLAGS"       ,"COMMAND"                 ,0 },
    {2107 ,"^COMMAND\\s+INFO"                  ,"COMMAND"                 ,0 },
    {2108 ,"^COMMAND\\s+LIST"                  ,"COMMAND"                 ,0 },
    {2109 ,"^CONFIG\\s+GET"                    ,"CONFIG"                  ,0 },
    {2110 ,"^CONFIG\\s+RESETSTAT"              ,"CONFIG"                  ,0 },
    {2111 ,"^CONFIG\\s+REWRITE"                ,"CONFIG"                  ,0 },
    {2112 ,"^CONFIG\\s+SET"                    ,"CONFIG"                  ,0 },
    {2113 ,"^COPY"                             ,"COPY"                    ,0 },
    {2114 ,"^DBSIZE"                           ,"DBSIZE"                  ,0 },
    {2115 ,"^DECR"                             ,"DECR"                    ,0 },
    {2116 ,"^DECRBY"                           ,"DECRBY"                  ,0 },
    {2117 ,"^DEL"                              ,"DEL"                     ,0 },
    {2118 ,"^DISCARD"                          ,"DISCARD"                 ,0 },
    {2119 ,"^DUMP"                             ,"DUMP"                    ,0 },
    {2120 ,"^ECHO"                             ,"ECHO"                    ,0 },
    {2121 ,"^EVAL"                             ,"EVAL"                    ,0 },
    {2122 ,"^EVAL_RO"                          ,"EVAL_RO"                 ,0 },
    {2123 ,"^EVALSHA"                          ,"EVALSHA"                 ,0 },
    {2124 ,"^EVALSHA_RO"                       ,"EVALSHA_RO"              ,0 },
    {2125 ,"^EXEC"                             ,"EXEC"                    ,0 },
    {2126 ,"^EXISTS"                           ,"EXISTS"                  ,0 },
    {2127 ,"^EXPIRE"                           ,"EXPIRE"                  ,0 },
    {2128 ,"^EXPIREAT"                         ,"EXPIREAT"                ,0 },
    {2129 ,"^EXPIRETIME"                       ,"EXPIRETIME"              ,0 },
    {2130 ,"^FAILOVER"                         ,"FAILOVER"                ,0 },
    {2131 ,"^FCALL"                            ,"FCALL"                   ,0 },
    {2132 ,"^FCALL_RO"                         ,"FCALL_RO"                ,0 },
    {2133 ,"^FLUSHALL"                         ,"FLUSHALL"                ,0 },
    {2134 ,"^FLUSHDB"                          ,"FLUSHDB"                 ,0 },
    {2135 ,"^FT\\._LIST"                       ,"FT"                      ,0 },
    {2136 ,"^FT\\.AGGREGATE"                   ,"FT"                      ,0 },
    {2137 ,"^FT\\.ALIASADD"                    ,"FT"                      ,0 },
    {2138 ,"^FT\\.ALIASDEL"                    ,"FT"                      ,0 },
    {2139 ,"^FT\\.ALIASUPDATE"                 ,"FT"                      ,0 },
    {2140 ,"^FT\\.ALTER"                       ,"FT"                      ,0 },
    {2141 ,"^FT\\.CONFIG\\s+GET"               ,"FT"                      ,0 },
    {2142 ,"^FT\\.CONFIG\\s+SET"               ,"FT"                      ,0 },
    {2143 ,"^FT\\.CREATE"                      ,"FT"                      ,0 },
    {2144 ,"^FT\\.CURSOR\\s+DEL"               ,"FT"                      ,0 },
    {2145 ,"^FT\\.CURSOR\\s+READ"              ,"FT"                      ,0 },
    {2146 ,"^FT\\.DICTADD"                     ,"FT"                      ,0 },
    {2147 ,"^FT\\.DICTDEL"                     ,"FT"                      ,0 },
    {2148 ,"^FT\\.DICTDUMP"                    ,"FT"                      ,0 },
    {2149 ,"^FT\\.DROPINDEX"                   ,"FT"                      ,0 },
    {2150 ,"^FT\\.EXPLAIN"                     ,"FT"                      ,0 },
    {2151 ,"^FT\\.EXPLAINCLI"                  ,"FT"                      ,0 },
    {2152 ,"^FT\\.INFO"                        ,"FT"                      ,0 },
    {2153 ,"^FT\\.PROFILE"                     ,"FT"                      ,0 },
    {2154 ,"^FT\\.SEARCH"                      ,"FT"                      ,0 },
    {2155 ,"^FT\\.SPELLCHECK"                  ,"FT"                      ,0 },
    {2156 ,"^FT\\.SUGADD"                      ,"FT"                      ,0 },
    {2157 ,"^FT\\.SUGDEL"                      ,"FT"                      ,0 },
    {2158 ,"^FT\\.SUGGET"                      ,"FT"                      ,0 },
    {2159 ,"^FT\\.SUGLEN"                      ,"FT"                      ,0 },
    {2160 ,"^FT\\.SYNDUMP"                     ,"FT"                      ,0 },
    {2161 ,"^FT\\.SYNUPDATE"                   ,"FT"                      ,0 },
    {2162 ,"^FT\\.TAGVALS"                     ,"FT"                      ,0 },
    {2163 ,"^FUNCTION\\s+DELETE"               ,"FUNCTION"                ,0 },
    {2164 ,"^FUNCTION\\s+DUMP"                 ,"FUNCTION"                ,0 },
    {2165 ,"^FUNCTION\\s+FLUSH"                ,"FUNCTION"                ,0 },
    {2166 ,"^FUNCTION\\s+KILL"                 ,"FUNCTION"                ,0 },
    {2167 ,"^FUNCTION\\s+LIST"                 ,"FUNCTION"                ,0 },
    {2168 ,"^FUNCTION\\s+LOAD"                 ,"FUNCTION"                ,0 },
    {2169 ,"^FUNCTION\\s+RESTORE"              ,"FUNCTION"                ,0 },
    {2170 ,"^FUNCTION\\s+STATS"                ,"FUNCTION"                ,0 },
    {2171 ,"^GEOADD"                           ,"GEOADD"                  ,0 },
    {2172 ,"^GEODIST"                          ,"GEODIST"                 ,0 },
    {2173 ,"^GEOHASH"                          ,"GEOHASH"                 ,0 },
    {2174 ,"^GEOPOS"                           ,"GEOPOS"                  ,0 },
    {2175 ,"^GEORADIUS"                        ,"GEORADIUS"               ,0 },
    {2176 ,"^GEORADIUS_RO"                     ,"GEORADIUS_RO"            ,0 },
    {2177 ,"^GEORADIUSBYMEMBER"                ,"GEORADIUSBYMEMBER"       ,0 },
    {2178 ,"^GEORADIUSBYMEMBER_RO"             ,"GEORADIUSBYMEMBER_RO"    ,0 },
    {2179 ,"^GEOSEARCH"                        ,"GEOSEARCH"               ,0 },
    {2180 ,"^GEOSEARCHSTORE"                   ,"GEOSEARCHSTORE"          ,0 },
    {2181 ,"^GET"                              ,"GET"                     ,0 },
    {2182 ,"^GETBIT"                           ,"GETBIT"                  ,0 },
    {2183 ,"^GETDEL"                           ,"GETDEL"                  ,0 },
    {2184 ,"^GETEX"                            ,"GETEX"                   ,0 },
    {2185 ,"^GETRANGE"                         ,"GETRANGE"                ,0 },
    {2186 ,"^GETSET"                           ,"GETSET"                  ,0 },
    {2187 ,"^HDEL"                             ,"HDEL"                    ,0 },
    {2188 ,"^HELLO"                            ,"HELLO"                   ,0 },
    {2189 ,"^HEXISTS"                          ,"HEXISTS"                 ,0 },
    {2190 ,"^HGET"                             ,"HGET"                    ,0 },
    {2191 ,"^HGETALL"                          ,"HGETALL"                 ,0 },
    {2192 ,"^HINCRBY"                          ,"HINCRBY"                 ,0 },
    {2193 ,"^HINCRBYFLOAT"                     ,"HINCRBYFLOAT"            ,0 },
    {2194 ,"^HKEYS"                            ,"HKEYS"                   ,0 },
    {2195 ,"^HLEN"                             ,"HLEN"                    ,0 },
    {2196 ,"^HMGET"                            ,"HMGET"                   ,0 },
    {2197 ,"^HMSET"                            ,"HMSET"                   ,0 },
    {2198 ,"^HRANDFIELD"                       ,"HRANDFIELD"              ,0 },
    {2199 ,"^HSCAN"                            ,"HSCAN"                   ,0 },
    {2200 ,"^HSET"                             ,"HSET"                    ,0 },
    {2201 ,"^HSETNX"                           ,"HSETNX"                  ,0 },
    {2202 ,"^HSTRLEN"                          ,"HSTRLEN"                 ,0 },
    {2203 ,"^HVALS"                            ,"HVALS"                   ,0 },
    {2204 ,"^INCR"                             ,"INCR"                    ,0 },
    {2205 ,"^INCRBY"                           ,"INCRBY"                  ,0 },
    {2206 ,"^INCRBYFLOAT"                      ,"INCRBYFLOAT"             ,0 },
    {2207 ,"^INFO"                             ,"INFO"                    ,0 },
    {2208 ,"^JSON\\.ARRAPPEND"                 ,"JSON"                    ,0 },
    {2209 ,"^JSON\\.ARRINDEX"                  ,"JSON"                    ,0 },
    {2210 ,"^JSON\\.ARRINSERT"                 ,"JSON"                    ,0 },
    {2211 ,"^JSON\\.ARRLEN"                    ,"JSON"                    ,0 },
    {2212 ,"^JSON\\.ARRPOP"                    ,"JSON"                    ,0 },
    {2213 ,"^JSON\\.ARRTRIM"                   ,"JSON"                    ,0 },
    {2214 ,"^JSON\\.CLEAR"                     ,"JSON"                    ,0 },
    {2215 ,"^JSON\\.DEBUG"                     ,"JSON"                    ,0 },
    {2216 ,"^JSON\\.DEBUG\\s+MEMORY"           ,"JSON"                    ,0 },
    {2217 ,"^JSON\\.DEL"                       ,"JSON"                    ,0 },
    {2218 ,"^JSON\\.FORGET"                    ,"JSON"                    ,0 },
    {2219 ,"^JSON\\.GET"                       ,"JSON"                    ,0 },
    {2220 ,"^JSON\\.MERGE"                     ,"JSON"                    ,0 },
    {2221 ,"^JSON\\.MGET"                      ,"JSON"                    ,0 },
    {2222 ,"^JSON\\.MSET"                      ,"JSON"                    ,0 },
    {2223 ,"^JSON\\.NUMINCRBY"                 ,"JSON"                    ,0 },
    {2224 ,"^JSON\\.NUMMULTBY"                 ,"JSON"                    ,0 },
    {2225 ,"^JSON\\.OBJKEYS"                   ,"JSON"                    ,0 },
    {2226 ,"^JSON\\.OBJLEN"                    ,"JSON"                    ,0 },
    {2227 ,"^JSON\\.RESP"                      ,"JSON"                    ,0 },
    {2228 ,"^JSON\\.SET"                       ,"JSON"                    ,0 },
    {2229 ,"^JSON\\.STRAPPEND"                 ,"JSON"                    ,0 },
    {2230 ,"^JSON\\.STRLEN"                    ,"JSON"                    ,0 },
    {2231 ,"^JSON\\.TOGGLE"                    ,"JSON"                    ,0 },
    {2232 ,"^JSON\\.TYPE"                      ,"JSON"                    ,0 },
    {2233 ,"^KEYS"                             ,"KEYS"                    ,0 },
    {2234 ,"^LASTSAVE"                         ,"LASTSAVE"                ,0 },
    {2235 ,"^LATENCY\\s+DOCTOR"                ,"LATENCY"                 ,0 },
    {2236 ,"^LATENCY\\s+GRAPH"                 ,"LATENCY"                 ,0 },
    {2237 ,"^LATENCY\\s+HISTOGRAM"             ,"LATENCY"                 ,0 },
    {2238 ,"^LATENCY\\s+HISTORY"               ,"LATENCY"                 ,0 },
    {2239 ,"^LATENCY\\s+LATEST"                ,"LATENCY"                 ,0 },
    {2240 ,"^LATENCY\\s+RESET"                 ,"LATENCY"                 ,0 },
    {2241 ,"^LCS"                              ,"LCS"                     ,0 },
    {2242 ,"^LINDEX"                           ,"LINDEX"                  ,0 },
    {2243 ,"^LINSERT"                          ,"LINSERT"                 ,0 },
    {2244 ,"^LLEN"                             ,"LLEN"                    ,0 },
    {2245 ,"^LMOVE"                            ,"LMOVE"                   ,0 },
    {2246 ,"^LMPOP"                            ,"LMPOP"                   ,0 },
    {2247 ,"^LOLWUT"                           ,"LOLWUT"                  ,0 },
    {2248 ,"^LPOP"                             ,"LPOP"                    ,0 },
    {2249 ,"^LPOS"                             ,"LPOS"                    ,0 },
    {2250 ,"^LPUSH"                            ,"LPUSH"                   ,0 },
    {2251 ,"^LPUSHX"                           ,"LPUSHX"                  ,0 },
    {2252 ,"^LRANGE"                           ,"LRANGE"                  ,0 },
    {2253 ,"^LREM"                             ,"LREM"                    ,0 },
    {2254 ,"^LSET"                             ,"LSET"                    ,0 },
    {2255 ,"^LTRIM"                            ,"LTRIM"                   ,0 },
    {2256 ,"^MEMORY\\s+DOCTOR"                 ,"MEMORY"                  ,0 },
    {2257 ,"^MEMORY\\s+MALLOC-STATS"           ,"MEMORY"                  ,0 },
    {2258 ,"^MEMORY\\s+PURGE"                  ,"MEMORY"                  ,0 },
    {2259 ,"^MEMORY\\s+STATS"                  ,"MEMORY"                  ,0 },
    {2260 ,"^MEMORY\\s+USAGE"                  ,"MEMORY"                  ,0 },
    {2261 ,"^MGET"                             ,"MGET"                    ,0 },
    {2262 ,"^MIGRATE"                          ,"MIGRATE"                 ,0 },
    {2263 ,"^MODULE\\s+LIST"                   ,"MODULE"                  ,0 },
    {2264 ,"^MODULE\\s+LOAD"                   ,"MODULE"                  ,0 },
    {2265 ,"^MODULE\\s+LOADEX"                 ,"MODULE"                  ,0 },
    {2266 ,"^MODULE\\s+UNLOAD"                 ,"MODULE"                  ,0 },
    {2267 ,"^MONITOR"                          ,"MONITOR"                 ,0 },
    {2268 ,"^MOVE"                             ,"MOVE"                    ,0 },
    {2269 ,"^MSET"                             ,"MSET"                    ,0 },
    {2270 ,"^MSETNX"                           ,"MSETNX"                  ,0 },
    {2271 ,"^MULTI"                            ,"MULTI"                   ,0 },
    {2272 ,"^OBJECT\\s+ENCODING"               ,"OBJECT"                  ,0 },
    {2273 ,"^OBJECT\\s+FREQ"                   ,"OBJECT"                  ,0 },
    {2274 ,"^OBJECT\\s+IDLETIME"               ,"OBJECT"                  ,0 },
    {2275 ,"^OBJECT\\s+REFCOUNT"               ,"OBJECT"                  ,0 },
    {2276 ,"^PERSIST"                          ,"PERSIST"                 ,0 },
    {2277 ,"^PEXPIRE"                          ,"PEXPIRE"                 ,0 },
    {2278 ,"^PEXPIREAT"                        ,"PEXPIREAT"               ,0 },
    {2279 ,"^PEXPIRETIME"                      ,"PEXPIRETIME"             ,0 },
    {2280 ,"^PFADD"                            ,"PFADD"                   ,0 },
    {2281 ,"^PFCOUNT"                          ,"PFCOUNT"                 ,0 },
    {2282 ,"^PFDEBUG"                          ,"PFDEBUG"                 ,0 },
    {2283 ,"^PFMERGE"                          ,"PFMERGE"                 ,0 },
    {2284 ,"^PFSELFTEST"                       ,"PFSELFTEST"              ,0 },
    {2285 ,"^PING"                             ,"PING"                    ,REDIS_CMD_TYPE_PING },
    {2286 ,"^PSETEX"                           ,"PSETEX"                  ,0 },
    {2287 ,"^PSUBSCRIBE"                       ,"PSUBSCRIBE"              ,0 },
    {2288 ,"^PSYNC"                            ,"PSYNC"                   ,0 },
    {2289 ,"^PTTL"                             ,"PTTL"                    ,0 },
    {2290 ,"^PUBLISH"                          ,"PUBLISH"                 ,0 },
    {2291 ,"^PUBSUB\\s+CHANNELS"               ,"PUBSUB"                  ,0 },
    {2292 ,"^PUBSUB\\s+NUMPAT"                 ,"PUBSUB"                  ,0 },
    {2293 ,"^PUBSUB\\s+NUMSUB"                 ,"PUBSUB"                  ,0 },
    {2294 ,"^PUBSUB\\s+SHARDCHANNELS"          ,"PUBSUB"                  ,0 },
    {2295 ,"^PUBSUB\\s+SHARDNUMSUB"            ,"PUBSUB"                  ,0 },
    {2296 ,"^PUNSUBSCRIBE"                     ,"PUNSUBSCRIBE"            ,0 },
    {2297 ,"^QUIT"                             ,"QUIT"                    ,REDIS_CMD_TYPE_QUIT },
    {2298 ,"^RANDOMKEY"                        ,"RANDOMKEY"               ,0 },
    {2299 ,"^READONLY"                         ,"READONLY"                ,0 },
    {2300 ,"^READWRITE"                        ,"READWRITE"               ,0 },
    {2301 ,"^RENAME"                           ,"RENAME"                  ,0 },
    {2302 ,"^RENAMENX"                         ,"RENAMENX"                ,0 },
    {2303 ,"^REPLCONF"                         ,"REPLCONF"                ,0 },
    {2304 ,"^REPLICAOF"                        ,"REPLICAOF"               ,0 },
    {2305 ,"^RESET"                            ,"RESET"                   ,0 },
    {2306 ,"^RESTORE"                          ,"RESTORE"                 ,0 },
    {2307 ,"^RESTORE-ASKING"                   ,"RESTORE-ASKING"          ,0 },
    {2308 ,"^ROLE"                             ,"ROLE"                    ,0 },
    {2309 ,"^RPOP"                             ,"RPOP"                    ,0 },
    {2310 ,"^RPOPLPUSH"                        ,"RPOPLPUSH"               ,0 },
    {2311 ,"^RPUSH"                            ,"RPUSH"                   ,0 },
    {2312 ,"^RPUSHX"                           ,"RPUSHX"                  ,0 },
    {2313 ,"^SADD"                             ,"SADD"                    ,0 },
    {2314 ,"^SAVE"                             ,"SAVE"                    ,0 },
    {2315 ,"^SCAN"                             ,"SCAN"                    ,0 },
    {2316 ,"^SCARD"                            ,"SCARD"                   ,0 },
    {2317 ,"^SCRIPT\\s+DEBUG"                  ,"SCRIPT"                  ,0 },
    {2318 ,"^SCRIPT\\s+EXISTS"                 ,"SCRIPT"                  ,0 },
    {2319 ,"^SCRIPT\\s+FLUSH"                  ,"SCRIPT"                  ,0 },
    {2320 ,"^SCRIPT\\s+KILL"                   ,"SCRIPT"                  ,0 },
    {2321 ,"^SCRIPT\\s+LOAD"                   ,"SCRIPT"                  ,0 },
    {2322 ,"^SDIFF"                            ,"SDIFF"                   ,0 },
    {2323 ,"^SDIFFSTORE"                       ,"SDIFFSTORE"              ,0 },
    {2324 ,"^SELECT"                           ,"SELECT"                  ,REDIS_CMD_TYPE_SELECT },
    {2325 ,"^SET\\s+"                          ,"SET"                     ,0 },
    {2326 ,"^SETBIT"                           ,"SETBIT"                  ,0 },
    {2327 ,"^SETEX"                            ,"SETEX"                   ,0 },
    {2328 ,"^SETNX"                            ,"SETNX"                   ,0 },
    {2329 ,"^SETRANGE"                         ,"SETRANGE"                ,0 },
    {2330 ,"^SHUTDOWN"                         ,"SHUTDOWN"                ,0 },
    {2331 ,"^SINTER"                           ,"SINTER"                  ,0 },
    {2332 ,"^SINTERCARD"                       ,"SINTERCARD"              ,0 },
    {2333 ,"^SINTERSTORE"                      ,"SINTERSTORE"             ,0 },
    {2334 ,"^SISMEMBER"                        ,"SISMEMBER"               ,0 },
    {2335 ,"^SLAVEOF"                          ,"SLAVEOF"                 ,0 },
    {2336 ,"^SLOWLOG\\s+GET"                   ,"SLOWLOG"                 ,0 },
    {2337 ,"^SLOWLOG\\s+LEN"                   ,"SLOWLOG"                 ,0 },
    {2338 ,"^SLOWLOG\\s+RESET"                 ,"SLOWLOG"                 ,0 },
    {2339 ,"^SMEMBERS"                         ,"SMEMBERS"                ,0 },
    {2340 ,"^SMISMEMBER"                       ,"SMISMEMBER"              ,0 },
    {2341 ,"^SMOVE"                            ,"SMOVE"                   ,0 },
    {2342 ,"^SORT"                             ,"SORT"                    ,0 },
    {2343 ,"^SORT_RO"                          ,"SORT_RO"                 ,0 },
    {2344 ,"^SPOP"                             ,"SPOP"                    ,0 },
    {2345 ,"^SPUBLISH"                         ,"SPUBLISH"                ,0 },
    {2346 ,"^SRANDMEMBER"                      ,"SRANDMEMBER"             ,0 },
    {2347 ,"^SREM"                             ,"SREM"                    ,0 },
    {2348 ,"^SSCAN"                            ,"SSCAN"                   ,0 },
    {2349 ,"^SSUBSCRIBE"                       ,"SSUBSCRIBE"              ,0 },
    {2350 ,"^STRLEN"                           ,"STRLEN"                  ,0 },
    {2351 ,"^SUBSCRIBE"                        ,"SUBSCRIBE"               ,0 },
    {2352 ,"^SUBSTR"                           ,"SUBSTR"                  ,0 },
    {2353 ,"^SUNION"                           ,"SUNION"                  ,0 },
    {2354 ,"^SUNIONSTORE"                      ,"SUNIONSTORE"             ,0 },
    {2355 ,"^SUNSUBSCRIBE"                     ,"SUNSUBSCRIBE"            ,0 },
    {2356 ,"^SWAPDB"                           ,"SWAPDB"                  ,0 },
    {2357 ,"^SYNC"                             ,"SYNC"                    ,0 },
    {2358 ,"^TDIGEST\\.ADD"                    ,"TDIGEST"                 ,0 },
    {2359 ,"^TDIGEST\\.BYRANK"                 ,"TDIGEST"                 ,0 },
    {2360 ,"^TDIGEST\\.BYREVRANK"              ,"TDIGEST"                 ,0 },
    {2361 ,"^TDIGEST\\.CDF"                    ,"TDIGEST"                 ,0 },
    {2362 ,"^TDIGEST\\.CREATE"                 ,"TDIGEST"                 ,0 },
    {2363 ,"^TDIGEST\\.INFO"                   ,"TDIGEST"                 ,0 },
    {2364 ,"^TDIGEST\\.MAX"                    ,"TDIGEST"                 ,0 },
    {2365 ,"^TDIGEST\\.MERGE"                  ,"TDIGEST"                 ,0 },
    {2366 ,"^TDIGEST\\.MIN"                    ,"TDIGEST"                 ,0 },
    {2367 ,"^TDIGEST\\.QUANTILE"               ,"TDIGEST"                 ,0 },
    {2368 ,"^TDIGEST\\.RANK"                   ,"TDIGEST"                 ,0 },
    {2369 ,"^TDIGEST\\.RESET"                  ,"TDIGEST"                 ,0 },
    {2370 ,"^TDIGEST\\.REVRANK"                ,"TDIGEST"                 ,0 },
    {2371 ,"^TDIGEST\\.TRIMMED_MEAN"           ,"TDIGEST"                 ,0 },
    {2372 ,"^TFCALL"                           ,"TFCALL"                  ,0 },
    {2373 ,"^TFCALLASYNC"                      ,"TFCALLASYNC"             ,0 },
    {2374 ,"^TFUNCTION\\s+DELETE"              ,"TFUNCTIONDELETE"         ,0 },
    {2375 ,"^TFUNCTION\\s+LIST"                ,"TFUNCTIONLIST"           ,0 },
    {2376 ,"^TFUNCTION\\s+LOAD"                ,"TFUNCTIONLOAD"           ,0 },
    {2377 ,"^TIME"                             ,"TIME"                    ,0 },
    {2378 ,"^TOPK\\.ADD"                       ,"TOPK"                    ,0 },
    {2379 ,"^TOPK\\.COUNT"                     ,"TOPK"                    ,0 },
    {2380 ,"^TOPK\\.INCRBY"                    ,"TOPK"                    ,0 },
    {2381 ,"^TOPK\\.INFO"                      ,"TOPK"                    ,0 },
    {2382 ,"^TOPK\\.LIST"                      ,"TOPK"                    ,0 },
    {2383 ,"^TOPK\\.QUERY"                     ,"TOPK"                    ,0 },
    {2384 ,"^TOPK\\.RESERVE"                   ,"TOPK"                    ,0 },
    {2385 ,"^TOUCH"                            ,"TOUCH"                   ,0 },
    {2386 ,"^TS\\.ADD"                         ,"TS"                      ,0 },
    {2387 ,"^TS\\.ALTER"                       ,"TS"                      ,0 },
    {2388 ,"^TS\\.CREATE"                      ,"TS"                      ,0 },
    {2389 ,"^TS\\.CREATERULE"                  ,"TS"                      ,0 },
    {2390 ,"^TS\\.DECRBY"                      ,"TS"                      ,0 },
    {2391 ,"^TS\\.DEL"                         ,"TS"                      ,0 },
    {2392 ,"^TS\\.DELETERULE"                  ,"TS"                      ,0 },
    {2393 ,"^TS\\.GET"                         ,"TS"                      ,0 },
    {2394 ,"^TS\\.INCRBY"                      ,"TS"                      ,0 },
    {2395 ,"^TS\\.INFO"                        ,"TS"                      ,0 },
    {2396 ,"^TS\\.MADD"                        ,"TS"                      ,0 },
    {2397 ,"^TS\\.MGET"                        ,"TS"                      ,0 },
    {2398 ,"^TS\\.MRANGE"                      ,"TS"                      ,0 },
    {2399 ,"^TS\\.MREVRANGE"                   ,"TS"                      ,0 },
    {2400 ,"^TS\\.QUERYINDEX"                  ,"TS"                      ,0 },
    {2401 ,"^TS\\.RANGE"                       ,"TS"                      ,0 },
    {2402 ,"^TS\\.REVRANGE"                    ,"TS"                      ,0 },
    {2403 ,"^TTL"                              ,"TTL"                     ,0 },
    {2404 ,"^TYPE"                             ,"TYPE"                    ,0 },
    {2405 ,"^UNLINK"                           ,"UNLINK"                  ,0 },
    {2406 ,"^UNSUBSCRIBE"                      ,"UNSUBSCRIBE"             ,0 },
    {2407 ,"^UNWATCH"                          ,"UNWATCH"                 ,0 },
    {2408 ,"^WAIT"                             ,"WAIT"                    ,0 },
    {2409 ,"^WAITAOF"                          ,"WAITAOF"                 ,0 },
    {2410 ,"^WATCH"                            ,"WATCH"                   ,0 },
    {2411 ,"^XACK"                             ,"XACK"                    ,0 },
    {2412 ,"^XADD"                             ,"XADD"                    ,0 },
    {2413 ,"^XAUTOCLAIM"                       ,"XAUTOCLAIM"              ,0 },
    {2414 ,"^XCLAIM"                           ,"XCLAIM"                  ,0 },
    {2415 ,"^XDEL"                             ,"XDEL"                    ,0 },
    {2416 ,"^XGROUP\\s+CREATE"                 ,"XGROUP"                  ,0 },
    {2417 ,"^XGROUP\\s+CREATECONSUMER"         ,"XGROUP"                  ,0 },
    {2418 ,"^XGROUP\\s+DELCONSUMER"            ,"XGROUP"                  ,0 },
    {2419 ,"^XGROUP\\s+DESTROY"                ,"XGROUP"                  ,0 },
    {2420 ,"^XGROUP\\s+SETID"                  ,"XGROUP"                  ,0 },
    {2421 ,"^XINFO\\s+CONSUMERS"               ,"XINFO"                   ,0 },
    {2422 ,"^XINFO\\s+GROUPS"                  ,"XINFO"                   ,0 },
    {2423 ,"^XINFO\\s+STREAM"                  ,"XINFO"                   ,0 },
    {2424 ,"^XLEN"                             ,"XLEN"                    ,0 },
    {2425 ,"^XPENDING"                         ,"XPENDING"                ,0 },
    {2426 ,"^XRANGE"                           ,"XRANGE"                  ,0 },
    {2427 ,"^XREAD"                            ,"XREAD"                   ,0 },
    {2428 ,"^XREADGROUP"                       ,"XREADGROUP"              ,0 },
    {2429 ,"^XREVRANGE"                        ,"XREVRANGE"               ,0 },
    {2430 ,"^XSETID"                           ,"XSETID"                  ,0 },
    {2431 ,"^XTRIM"                            ,"XTRIM"                   ,0 },
    {2432 ,"^ZADD"                             ,"ZADD"                    ,0 },
    {2433 ,"^ZCARD"                            ,"ZCARD"                   ,0 },
    {2434 ,"^ZCOUNT"                           ,"ZCOUNT"                  ,0 },
    {2435 ,"^ZDIFF"                            ,"ZDIFF"                   ,0 },
    {2436 ,"^ZDIFFSTORE"                       ,"ZDIFFSTORE"              ,0 },
    {2437 ,"^ZINCRBY"                          ,"ZINCRBY"                 ,0 },
    {2438 ,"^ZINTER"                           ,"ZINTER"                  ,0 },
    {2439 ,"^ZINTERCARD"                       ,"ZINTERCARD"              ,0 },
    {2440 ,"^ZINTERSTORE"                      ,"ZINTERSTORE"             ,0 },
    {2441 ,"^ZLEXCOUNT"                        ,"ZLEXCOUNT"               ,0 },
    {2442 ,"^ZMPOP"                            ,"ZMPOP"                   ,0 },
    {2443 ,"^ZMSCORE"                          ,"ZMSCORE"                 ,0 },
    {2444 ,"^ZPOPMAX"                          ,"ZPOPMAX"                 ,0 },
    {2445 ,"^ZPOPMIN"                          ,"ZPOPMIN"                 ,0 },
    {2446 ,"^ZRANDMEMBER"                      ,"ZRANDMEMBER"             ,0 },
    {2447 ,"^ZRANGE"                           ,"ZRANGE"                  ,0 },
    {2448 ,"^ZRANGEBYLEX"                      ,"ZRANGEBYLEX"             ,0 },
    {2449 ,"^ZRANGEBYSCORE"                    ,"ZRANGEBYSCORE"           ,0 },
    {2450 ,"^ZRANGESTORE"                      ,"ZRANGESTORE"             ,0 },
    {2451 ,"^ZRANK"                            ,"ZRANK"                   ,0 },
    {2452 ,"^ZREM"                             ,"ZREM"                    ,0 },
    {2453 ,"^ZREMRANGEBYLEX"                   ,"ZREMRANGEBYLEX"          ,0 },
    {2454 ,"^ZREMRANGEBYRANK"                  ,"ZREMRANGEBYRANK"         ,0 },
    {2455 ,"^ZREMRANGEBYSCORE"                 ,"ZREMRANGEBYSCORE"        ,0 },
    {2456 ,"^ZREVRANGE"                        ,"ZREVRANGE"               ,0 },
    {2457 ,"^ZREVRANGEBYLEX"                   ,"ZREVRANGEBYLEX"          ,0 },
    {2458 ,"^ZREVRANGEBYSCORE"                 ,"ZREVRANGEBYSCORE"        ,0 },
    {2459 ,"^ZREVRANK"                         ,"ZREVRANK"                ,0 },
    {2460 ,"^ZSCAN"                            ,"ZSCAN"                   ,0 },
    {2461 ,"^ZSCORE"                           ,"ZSCORE"                  ,0 },
    {2462 ,"^ZUNION"                           ,"ZUNION"                  ,0 },
    {2463 ,"^ZUNIONSTORE"                      ,"ZUNIONSTORE"             ,0 },

    };

    auto ok = audit_hs_block_compile(g_hs_handler, _statements, sizeof(_statements)/sizeof(_statements[0]));
    if (!ok) {
        audit_hs_block_free(g_hs_handler);
        g_hs_handler = nullptr;
        return false;
    }

    /* everything is ready */
    return true;
}


void redis_statement_free(void)
{
    if (g_hs_handler) {
        audit_hs_block_free(g_hs_handler);
        g_hs_handler = nullptr;
    }
}


const audit_hs_data_t* redis_statement_analysis(audit_str_t& statement)
{
     return audit_hs_block_scan(g_hs_handler, statement.c_str(), (unsigned int)statement.size());
}

/*****************************************************************************/

